# -*- coding: utf-8 -*-
"""雅思核心词库 (IELTS Words)
本地离线词库，不依赖任何外部 API。
每条: word 单词 / phon 音标(IPA) / pos 词性 / mean 中文释义 /
      ex 英文例句 / ex_zh 例句中文翻译
每日由 workbench.py 按日期轮换抽取 15 个词。
"""
IELTS_WORDS = [
    # ---- 基础高频动词 ----
    {"word": "abandon", "phon": "/əˈbændən/", "pos": "v.", "mean": "放弃；抛弃", "ex": "They had to abandon the plan due to lack of funds.", "ex_zh": "由于资金不足，他们不得不放弃该计划。"},
    {"word": "achieve", "phon": "/əˈtʃiːv/", "pos": "v.", "mean": "实现；达到", "ex": "She achieved her goal through hard work.", "ex_zh": "她通过努力实现了目标。"},
    {"word": "analyze", "phon": "/ˈænəlaɪz/", "pos": "v.", "mean": "分析", "ex": "We need to analyze the data before drawing a conclusion.", "ex_zh": "下结论前我们需要分析数据。"},
    {"word": "assess", "phon": "/əˈses/", "pos": "v.", "mean": "评估；评定", "ex": "The teacher will assess each student's progress.", "ex_zh": "老师将评估每位学生的进步。"},
    {"word": "assume", "phon": "/əˈsjuːm/", "pos": "v.", "mean": "假设；认为", "ex": "We assume that the economy will recover next year.", "ex_zh": "我们假设经济明年会复苏。"},
    {"word": "commit", "phon": "/kəˈmɪt/", "pos": "v.", "mean": "承诺；犯（错）", "ex": "The government committed to reducing emissions.", "ex_zh": "政府承诺减少排放。"},
    {"word": "comprehend", "phon": "/ˌkɒmprɪˈhend/", "pos": "v.", "mean": "理解；领会", "ex": "It is hard to comprehend the scale of the universe.", "ex_zh": "很难理解宇宙的尺度。"},
    {"word": "demonstrate", "phon": "/ˈdemənstreɪt/", "pos": "v.", "mean": "证明；演示", "ex": "The study demonstrates a clear link between diet and health.", "ex_zh": "该研究证明了饮食与健康之间的明确联系。"},
    {"word": "enhance", "phon": "/ɪnˈhɑːns/", "pos": "v.", "mean": "提高；增强", "ex": "Good lighting enhances the atmosphere of a room.", "ex_zh": "良好的采光能提升房间的氛围。"},
    {"word": "establish", "phon": "/ɪˈstæblɪʃ/", "pos": "v.", "mean": "建立；确立", "ex": "The company established a new office in Asia.", "ex_zh": "该公司在亚洲设立了新办事处。"},
    {"word": "evaluate", "phon": "/ɪˈvæljueɪt/", "pos": "v.", "mean": "评价；估值", "ex": "We should evaluate the risks before investing.", "ex_zh": "投资前我们应先评估风险。"},
    {"word": "evolve", "phon": "/ɪˈvɒlv/", "pos": "v.", "mean": "进化；逐步发展", "ex": "Technology continues to evolve at a rapid pace.", "ex_zh": "技术持续快速发展。"},
    {"word": "expand", "phon": "/ɪkˈspænd/", "pos": "v.", "mean": "扩张；扩展", "ex": "The business expanded into overseas markets.", "ex_zh": "业务拓展至海外市场。"},
    {"word": "identify", "phon": "/aɪˈdentɪfaɪ/", "pos": "v.", "mean": "识别；确认", "ex": "Can you identify the main cause of the problem?", "ex_zh": "你能确认问题的主要原因吗？"},
    {"word": "implement", "phon": "/ˈɪmplɪment/", "pos": "v.", "mean": "实施；执行", "ex": "The new policy will be implemented next month.", "ex_zh": "新政策将于下月实施。"},
    {"word": "maintain", "phon": "/meɪnˈteɪn/", "pos": "v.", "mean": "维持；保养", "ex": "It is important to maintain a balanced diet.", "ex_zh": "保持均衡饮食很重要。"},
    {"word": "obtain", "phon": "/əbˈteɪn/", "pos": "v.", "mean": "获得；得到", "ex": "He obtained a degree in engineering.", "ex_zh": "他获得了工程学位。"},
    {"word": "promote", "phon": "/prəˈməʊt/", "pos": "v.", "mean": "促进；推广", "ex": "Exercise promotes both physical and mental health.", "ex_zh": "运动促进身心双重健康。"},
    {"word": "reduce", "phon": "/rɪˈdjuːs/", "pos": "v.", "mean": "减少；降低", "ex": "We must reduce our reliance on fossil fuels.", "ex_zh": "我们必须减少对化石燃料的依赖。"},
    {"word": "reveal", "phon": "/rɪˈviːl/", "pos": "v.", "mean": "揭示；显露", "ex": "The report reveals a worrying trend.", "ex_zh": "报告揭示了一个令人担忧的趋势。"},
    {"word": "substitute", "phon": "/ˈsʌbstɪtjuːt/", "pos": "v.", "mean": "替代", "ex": "You can substitute butter with oil in this recipe.", "ex_zh": "这个食谱里你可以用油代替黄油。"},
    {"word": "transform", "phon": "/trænsˈfɔːm/", "pos": "v.", "mean": "使改变；改造", "ex": "The internet transformed how we communicate.", "ex_zh": "互联网改变了我们的交流方式。"},
    {"word": "undertake", "phon": "/ˌʌndəˈteɪk/", "pos": "v.", "mean": "承担；着手做", "ex": "The firm undertook a major research project.", "ex_zh": "该公司承担了一个大型研究项目。"},

    # ---- 名词 ----
    {"word": "advantage", "phon": "/ədˈvɑːntɪdʒ/", "pos": "n.", "mean": "优势；好处", "ex": "One advantage of cycling is low cost.", "ex_zh": "骑自行车的一个好处是成本低。"},
    {"word": "benefit", "phon": "/ˈbenɪfɪt/", "pos": "n.", "mean": "益处；福利", "ex": "Regular exercise brings many health benefits.", "ex_zh": "规律运动带来诸多健康益处。"},
    {"word": "challenge", "phon": "/ˈtʃælɪndʒ/", "pos": "n.", "mean": "挑战", "ex": "Climate change is a global challenge.", "ex_zh": "气候变化是一项全球性挑战。"},
    {"word": "consequence", "phon": "/ˈkɒnsɪkwəns/", "pos": "n.", "mean": "后果；结果", "ex": "The consequence of the decision was unexpected.", "ex_zh": "这个决定的后果出乎意料。"},
    {"word": "contribution", "phon": "/ˌkɒntrɪˈbjuːʃən/", "pos": "n.", "mean": "贡献", "ex": "Her contribution to the team was significant.", "ex_zh": "她对团队的贡献很大。"},
    {"word": "crisis", "phon": "/ˈkraɪsɪs/", "pos": "n.", "mean": "危机", "ex": "The country is facing an economic crisis.", "ex_zh": "该国正面临一场经济危机。"},
    {"word": "distribution", "phon": "/ˌdɪstrɪˈbjuːʃən/", "pos": "n.", "mean": "分布；分配", "ex": "The distribution of wealth remains unequal.", "ex_zh": "财富分配仍然不均。"},
    {"word": "element", "phon": "/ˈelɪmənt/", "pos": "n.", "mean": "要素；元素", "ex": "Trust is a key element of teamwork.", "ex_zh": "信任是团队合作的关键要素。"},
    {"word": "environment", "phon": "/ɪnˈvaɪərənmənt/", "pos": "n.", "mean": "环境", "ex": "We must protect the natural environment.", "ex_zh": "我们必须保护自然环境。"},
    {"word": "evidence", "phon": "/ˈevɪdəns/", "pos": "n.", "mean": "证据；迹象", "ex": "There is no evidence to support the claim.", "ex_zh": "没有证据支持这一说法。"},
    {"word": "factor", "phon": "/ˈfæktə/", "pos": "n.", "mean": "因素", "ex": "Price is a key factor in consumer choice.", "ex_zh": "价格是消费者选择的关键因素。"},
    {"word": "feature", "phon": "/ˈfiːtʃə/", "pos": "n.", "mean": "特征；特色", "ex": "A unique feature of the app is offline mode.", "ex_zh": "该应用的一个独特功能是离线模式。"},
    {"word": "framework", "phon": "/ˈfreɪmwɜːk/", "pos": "n.", "mean": "框架；结构", "ex": "We need a legal framework for data privacy.", "ex_zh": "我们需要一个数据隐私的法律框架。"},
    {"word": "function", "phon": "/ˈfʌŋkʃən/", "pos": "n.", "mean": "功能；作用", "ex": "The main function of the heart is to pump blood.", "ex_zh": "心脏的主要功能是泵血。"},
    {"word": "impact", "phon": "/ˈɪmpækt/", "pos": "n.", "mean": "影响；冲击", "ex": "Social media has a huge impact on youth.", "ex_zh": "社交媒体对年轻人影响巨大。"},
    {"word": "income", "phon": "/ˈɪnkʌm/", "pos": "n.", "mean": "收入", "ex": "Household income has risen this year.", "ex_zh": "今年家庭收入有所上升。"},
    {"word": "infrastructure", "phon": "/ˈɪnfrəstrʌktʃə/", "pos": "n.", "mean": "基础设施", "ex": "The city invested in transport infrastructure.", "ex_zh": "该市投资了交通基础设施。"},
    {"word": "issue", "phon": "/ˈɪʃuː/", "pos": "n.", "mean": "问题；议题", "ex": "Poverty remains a serious social issue.", "ex_zh": "贫困仍是一个严重的社会问题。"},
    {"word": "labour", "phon": "/ˈleɪbə/", "pos": "n.", "mean": "劳动力；劳动", "ex": "The sector suffers from a shortage of skilled labour.", "ex_zh": "该行业面临技术劳动力短缺。"},
    {"word": "objective", "phon": "/əbˈdʒektɪv/", "pos": "n.", "mean": "目标；目的", "ex": "The objective of the project is to cut costs.", "ex_zh": "该项目的目标是降低成本。"},
    {"word": "phenomenon", "phon": "/fəˈnɒmɪnən/", "pos": "n.", "mean": "现象", "ex": "Global warming is a worrying phenomenon.", "ex_zh": "全球变暖是一个令人担忧的现象。"},
    {"word": "policy", "phon": "/ˈpɒləsi/", "pos": "n.", "mean": "政策；方针", "ex": "The government announced a new housing policy.", "ex_zh": "政府宣布了新的住房政策。"},
    {"word": "process", "phon": "/ˈprəʊses/", "pos": "n.", "mean": "过程；流程", "ex": "Learning a language is a long process.", "ex_zh": "学习一门语言是个漫长的过程。"},
    {"word": "resource", "phon": "/rɪˈsɔːs/", "pos": "n.", "mean": "资源", "ex": "Water is a precious natural resource.", "ex_zh": "水是一种宝贵的自然资源。"},
    {"word": "restriction", "phon": "/rɪˈstrɪkʃən/", "pos": "n.", "mean": "限制；约束", "ex": "There are restrictions on foreign investment.", "ex_zh": "对外国投资存在限制。"},
    {"word": "significance", "phon": "/sɪɡˈnɪfɪkəns/", "pos": "n.", "mean": "重要性；意义", "ex": "The discovery is of great scientific significance.", "ex_zh": "这一发现具有重大科学意义。"},
    {"word": "strategy", "phon": "/ˈstrætədʒi/", "pos": "n.", "mean": "策略；战略", "ex": "A clear strategy is vital for success.", "ex_zh": "清晰的策略对成功至关重要。"},
    {"word": "tendency", "phon": "/ˈtendənsi/", "pos": "n.", "mean": "趋势；倾向", "ex": "There is a tendency to work longer hours.", "ex_zh": "存在工作时间延长的趋势。"},

    # ---- 形容词 ----
    {"word": "adequate", "phon": "/ˈædɪkwət/", "pos": "adj.", "mean": "足够的；适当的", "ex": "The supply of food was adequate for all.", "ex_zh": "食物供给足够所有人。"},
    {"word": "apparent", "phon": "/əˈpærənt/", "pos": "adj.", "mean": "明显的；表面的", "ex": "The reason is apparent to everyone.", "ex_zh": "原因对所有人来说都显而易见。"},
    {"word": "appropriate", "phon": "/əˈprəʊpriət/", "pos": "adj.", "mean": "合适的；恰当的", "ex": "Choose an appropriate response for the situation.", "ex_zh": "为情境选择合适的回应。"},
    {"word": "crucial", "phon": "/ˈkruːʃəl/", "pos": "adj.", "mean": "关键的；至关重要的", "ex": "Communication is crucial in a relationship.", "ex_zh": "沟通在关系中至关重要。"},
    {"word": "distinct", "phon": "/dɪˈstɪŋkt/", "pos": "adj.", "mean": "明显的；不同的", "ex": "The two cultures have distinct traditions.", "ex_zh": "两种文化有不同的传统。"},
    {"word": "diverse", "phon": "/daɪˈvɜːs/", "pos": "adj.", "mean": "多样的；不同的", "ex": "The city has a diverse population.", "ex_zh": "这座城市人口多样。"},
    {"word": "efficient", "phon": "/ɪˈfɪʃənt/", "pos": "adj.", "mean": "高效的", "ex": "The new system is more efficient than the old one.", "ex_zh": "新系统比旧系统更高效。"},
    {"word": "essential", "phon": "/ɪˈsenʃəl/", "pos": "adj.", "mean": "必要的；本质的", "ex": "Sleep is essential for good health.", "ex_zh": "睡眠对健康必不可少。"},
    {"word": "feasible", "phon": "/ˈfiːzəbl/", "pos": "adj.", "mean": "可行的", "ex": "Is the plan financially feasible?", "ex_zh": "这个计划在财务上可行吗？"},
    {"word": "fundamental", "phon": "/ˌfʌndəˈmentl/", "pos": "adj.", "mean": "基本的；根本的", "ex": "Trust is fundamental to any friendship.", "ex_zh": "信任是任何友谊的根本。"},
    {"word": "inevitable", "phon": "/ɪnˈevɪtəbl/", "pos": "adj.", "mean": "不可避免的", "ex": "Change is inevitable in a growing company.", "ex_zh": "成长中的公司变化不可避免。"},
    {"word": "optimum", "phon": "/ˈɒptɪməm/", "pos": "adj.", "mean": "最佳的；最优的", "ex": "The optimum temperature for the plant is 20C.", "ex_zh": "这种植物的最佳温度是 20 摄氏度。"},
    {"word": "potential", "phon": "/pəˈtenʃəl/", "pos": "adj.", "mean": "潜在的；可能的", "ex": "The area has potential for tourism.", "ex_zh": "该地区有旅游潜力。"},
    {"word": "prior", "phon": "/ˈpraɪə/", "pos": "adj.", "mean": "先前的；优先的", "ex": "Prior experience is not required.", "ex_zh": "不需要先前经验。"},
    {"word": "relevant", "phon": "/ˈreləvənt/", "pos": "adj.", "mean": "相关的", "ex": "Please provide relevant examples.", "ex_zh": "请提供相关例子。"},
    {"word": "significant", "phon": "/sɪɡˈnɪfɪkənt/", "pos": "adj.", "mean": "重大的；显著的", "ex": "There was a significant drop in sales.", "ex_zh": "销售额显著下降。"},
    {"word": "stable", "phon": "/ˈsteɪbl/", "pos": "adj.", "mean": "稳定的", "ex": "The patient is now in a stable condition.", "ex_zh": "病人目前情况稳定。"},
    {"word": "substantial", "phon": "/səbˈstænʃl/", "pos": "adj.", "mean": "大量的；实质的", "ex": "The project requires substantial investment.", "ex_zh": "该项目需要大量投资。"},
    {"word": "sustainable", "phon": "/səˈsteɪnəbl/", "pos": "adj.", "mean": "可持续的", "ex": "We need a sustainable energy policy.", "ex_zh": "我们需要可持续的能源政策。"},
    {"word": "unprecedented", "phon": "/ʌnˈpresɪdentɪd/", "pos": "adj.", "mean": "前所未有的", "ex": "The pandemic caused unprecedented disruption.", "ex_zh": "疫情造成了前所未有的混乱。"},
    {"word": "vital", "phon": "/ˈvaɪtl/", "pos": "adj.", "mean": "至关重要的", "ex": "Clean water is vital to public health.", "ex_zh": "洁净水对公共健康至关重要。"},

    # ---- 学术 / 写作高频 ----
    {"word": "acknowledge", "phon": "/əkˈnɒlɪdʒ/", "pos": "v.", "mean": "承认；致谢", "ex": "We acknowledge the limitations of this study.", "ex_zh": "我们承认本研究的局限性。"},
    {"word": "contradict", "phon": "/ˌkɒntrəˈdɪkt/", "pos": "v.", "mean": "反驳；与…矛盾", "ex": "The data contradicts the earlier theory.", "ex_zh": "数据与早期理论矛盾。"},
    {"word": "derive", "phon": "/dɪˈraɪv/", "pos": "v.", "mean": "源于；派生", "ex": "The word is derived from Latin.", "ex_zh": "这个词源于拉丁语。"},
    {"word": "distinguish", "phon": "/dɪˈstɪŋɡwɪʃ/", "pos": "v.", "mean": "区分；辨别", "ex": "It is hard to distinguish the two species.", "ex_zh": "很难区分这两个物种。"},
    {"word": "emphasize", "phon": "/ˈemfəsaɪz/", "pos": "v.", "mean": "强调", "ex": "The report emphasizes the need for action.", "ex_zh": "报告强调了采取行动的必要性。"},
    {"word": "facilitate", "phon": "/fəˈsɪlɪteɪt/", "pos": "v.", "mean": "促进；使便利", "ex": "Good design facilitates learning.", "ex_zh": "好的设计促进学习。"},
    {"word": "illustrate", "phon": "/ˈɪləstreɪt/", "pos": "v.", "mean": "说明；图解", "ex": "The chart illustrates the trend clearly.", "ex_zh": "图表清楚地说明了趋势。"},
    {"word": "interpret", "phon": "/ɪnˈtɜːprɪt/", "pos": "v.", "mean": "解释；解读", "ex": "How do you interpret these results?", "ex_zh": "你如何解读这些结果？"},
    {"word": "justify", "phon": "/ˈdʒʌstɪfaɪ/", "pos": "v.", "mean": "证明…合理", "ex": "You must justify your conclusion with evidence.", "ex_zh": "你必须用证据证明结论的合理性。"},
    {"word": "overestimate", "phon": "/ˌəʊvərˈestɪmeɪt/", "pos": "v.", "mean": "高估", "ex": "Do not overestimate your ability to focus.", "ex_zh": "不要高估自己的专注力。"},
    {"word": "paradox", "phon": "/ˈpærədɒks/", "pos": "n.", "mean": "悖论；矛盾", "ex": "It is a paradox that we feel lonely in crowds.", "ex_zh": "在人群中感到孤独是一种悖论。"},
    {"word": "perspective", "phon": "/pəˈspektɪv/", "pos": "n.", "mean": "视角；观点", "ex": "The book offers a new perspective on history.", "ex_zh": "这本书提供了看待历史的新视角。"},
    {"word": "proportion", "phon": "/prəˈpɔːʃən/", "pos": "n.", "mean": "比例；部分", "ex": "A large proportion of users are under 30.", "ex_zh": "很大比例的用户在 30 岁以下。"},
    {"word": "reluctant", "phon": "/rɪˈlʌktənt/", "pos": "adj.", "mean": "不情愿的", "ex": "He was reluctant to admit the mistake.", "ex_zh": "他不情愿承认错误。"},
    {"word": "subsequent", "phon": "/ˈsʌbsɪkwənt/", "pos": "adj.", "mean": "随后的；后来的", "ex": "The subsequent tests confirmed the result.", "ex_zh": "随后的测试证实了结果。"},
    {"word": "therefore", "phon": "/ˈðeəfɔː/", "pos": "adv.", "mean": "因此；所以", "ex": "The cost was high; therefore we declined.", "ex_zh": "成本很高，因此我们拒绝了。"},
    {"word": "threshold", "phon": "/ˈθreʃhəʊld/", "pos": "n.", "mean": "门槛；临界点", "ex": "We are near the threshold of a breakthrough.", "ex_zh": "我们接近突破的临界点。"},
    {"word": "transmit", "phon": "/trænzˈmɪt/", "pos": "v.", "mean": "传播；传输", "ex": "Mosquitoes transmit the disease.", "ex_zh": "蚊子传播这种疾病。"},
    {"word": "undermine", "phon": "/ˌʌndəˈmaɪn/", "pos": "v.", "mean": "削弱；损害", "ex": "Rumours undermine team morale.", "ex_zh": "谣言削弱团队士气。"},
    {"word": "utilize", "phon": "/ˈjuːtəlaɪz/", "pos": "v.", "mean": "利用；使用", "ex": "We should utilize renewable energy.", "ex_zh": "我们应当利用可再生能源。"},
    {"word": "virtually", "phon": "/ˈvɜːtʃuəli/", "pos": "adv.", "mean": "几乎；实质上", "ex": "The task was virtually impossible.", "ex_zh": "这项任务几乎不可能完成。"},
    {"word": "widespread", "phon": "/ˈwaɪdspred/", "pos": "adj.", "mean": "广泛的；普遍的", "ex": "There is widespread support for the plan.", "ex_zh": "该计划得到广泛支持。"},
    {"word": "nevertheless", "phon": "/ˌnevəðəˈles/", "pos": "adv.", "mean": "然而；尽管如此", "ex": "It was hard; nevertheless she persisted.", "ex_zh": "这很难，但她仍然坚持。"},
    {"word": "accumulate", "phon": "/əˈkjuːmjəleɪt/", "pos": "v.", "mean": "积累；积聚", "ex": "Debt can accumulate quickly.", "ex_zh": "债务可能迅速累积。"},
    {"word": "allocate", "phon": "/ˈæləkeɪt/", "pos": "v.", "mean": "分配；拨出", "ex": "Funds were allocated to education.", "ex_zh": "资金被分配给教育。"},
    {"word": "coincide", "phon": "/ˌkəʊɪnˈsaɪd/", "pos": "v.", "mean": "同时发生；一致", "ex": "Our views coincide on this issue.", "ex_zh": "在这个问题上我们的观点一致。"},
    {"word": "compile", "phon": "/kəmˈpaɪl/", "pos": "v.", "mean": "编制；汇编", "ex": "They compiled a report from the data.", "ex_zh": "他们根据数据编制了一份报告。"},
    {"word": "consensus", "phon": "/kənˈsensəs/", "pos": "n.", "mean": "共识", "ex": "There is a broad consensus on the goal.", "ex_zh": "目标上达成了广泛共识。"},
    {"word": "contemporary", "phon": "/kənˈtemprəri/", "pos": "adj.", "mean": "当代的；同时代的", "ex": "The museum shows contemporary art.", "ex_zh": "该博物馆展出当代艺术。"},
    {"word": "discrete", "phon": "/dɪˈskriːt/", "pos": "adj.", "mean": "离散的；独立的", "ex": "The steps are discrete and measurable.", "ex_zh": "这些步骤是独立且可衡量的。"},
    {"word": "explicit", "phon": "/ɪkˈsplɪsɪt/", "pos": "adj.", "mean": "明确的；清楚的", "ex": "Please give explicit instructions.", "ex_zh": "请给出明确的指示。"},
    {"word": "feasibility", "phon": "/ˌfiːzəˈbɪləti/", "pos": "n.", "mean": "可行性", "ex": "We studied the feasibility of the idea.", "ex_zh": "我们研究了该想法的可行性。"},
    {"word": "inhomogeneous", "phon": "/ɪnˌhɒməˈdʒiːniəs/", "pos": "adj.", "mean": "不均匀的", "ex": "The mixture is inhomogeneous.", "ex_zh": "该混合物是不均匀的。"},
    {"word": "magnitude", "phon": "/ˈmæɡnɪtjuːd/", "pos": "n.", "mean": "量级；巨大", "ex": "We underestimated the magnitude of the problem.", "ex_zh": "我们低估了问题的量级。"},
    {"word": "mediate", "phon": "/ˈmiːdieɪt/", "pos": "v.", "mean": "调解；斡旋", "ex": "A third party mediated the dispute.", "ex_zh": "第三方调解了争端。"},
    {"word": "notion", "phon": "/ˈnəʊʃən/", "pos": "n.", "mean": "概念；想法", "ex": "He has no notion of the risk.", "ex_zh": "他对风险毫无概念。"},
    {"word": "phenomenal", "phon": "/fəˈnɒmɪnl/", "pos": "adj.", "mean": "非凡的；惊人的", "ex": "The growth was phenomenal last year.", "ex_zh": "去年的增长惊人。"},
    {"word": "prerequisite", "phon": "/ˌpriːˈrekwəzɪt/", "pos": "n.", "mean": "先决条件", "ex": "A degree is a prerequisite for the role.", "ex_zh": "学位是该职位的先决条件。"},
    {"word": "radical", "phon": "/ˈrædɪkl/", "pos": "adj.", "mean": "根本的；激进的", "ex": "The reform calls for radical change.", "ex_zh": "改革要求根本性改变。"},
    {"word": "relatively", "phon": "/ˈrelətɪvli/", "pos": "adv.", "mean": "相对地", "ex": "The task is relatively simple.", "ex_zh": "这项任务相对简单。"},
    {"word": "simultaneously", "phon": "/ˌsɪmlˈteɪniəsli/", "pos": "adv.", "mean": "同时地", "ex": "The events occurred simultaneously.", "ex_zh": "这些事件同时发生。"},
    {"word": "stability", "phon": "/stəˈbɪləti/", "pos": "n.", "mean": "稳定性", "ex": "Price stability benefits consumers.", "ex_zh": "价格稳定有利于消费者。"},
    {"word": "theoretically", "phon": "/ˌθɪəˈretɪkli/", "pos": "adv.", "mean": "理论上", "ex": "Theoretically, it should work.", "ex_zh": "理论上它应该可行。"},
    {"word": "whereas", "phon": "/ˈweəræz/", "pos": "conj.", "mean": "然而；鉴于", "ex": "He is rich whereas his brother is poor.", "ex_zh": "他很富有，而他弟弟很穷。"},
    {"word": "abundant", "phon": "/əˈbʌndənt/", "pos": "adj.", "mean": "丰富的；充裕的", "ex": "The region has abundant natural resources.", "ex_zh": "该地区自然资源丰富。"},
    {"word": "coherent", "phon": "/kəʊˈhɪərənt/", "pos": "adj.", "mean": "连贯的；有条理的", "ex": "She gave a coherent account of the event.", "ex_zh": "她对事件作了连贯的描述。"},
    {"word": "compelling", "phon": "/kəmˈpelɪŋ/", "pos": "adj.", "mean": "引人注目的；令人信服的", "ex": "The evidence is compelling.", "ex_zh": "证据令人信服。"},
    {"word": "concrete", "phon": "/ˈkɒŋkriːt/", "pos": "adj.", "mean": "具体的；实在的", "ex": "We need concrete examples, not vague ideas.", "ex_zh": "我们需要具体例子，而非模糊想法。"},
    {"word": "consistent", "phon": "/kənˈsɪstənt/", "pos": "adj.", "mean": "一致的；始终如一的", "ex": "His story was consistent with the facts.", "ex_zh": "他的说法与事实一致。"},
    {"word": "deliberate", "phon": "/dɪˈlɪbərət/", "pos": "adj.", "mean": "故意的；深思熟虑的", "ex": "The act was a deliberate protest.", "ex_zh": "该行为是蓄意的抗议。"},
    {"word": "homogeneous", "phon": "/ˌhɒməˈdʒiːniəs/", "pos": "adj.", "mean": "同质的；均匀的", "ex": "The sample was homogeneous.", "ex_zh": "样本是均匀的。"},
    {"word": "inequality", "phon": "/ˌɪnɪˈkwɒləti/", "pos": "n.", "mean": "不平等", "ex": "Income inequality is rising.", "ex_zh": "收入不平等在加剧。"},
    {"word": "inevitably", "phon": "/ɪnˈevɪtəbli/", "pos": "adv.", "mean": "不可避免地", "ex": "Prices will inevitably rise.", "ex_zh": "价格将不可避免地上涨。"},
    {"word": "integral", "phon": "/ˈɪntɪɡrəl/", "pos": "adj.", "mean": "构成整体所必须的", "ex": "Trust is integral to teamwork.", "ex_zh": "信任是团队合作的必要部分。"},
    {"word": "intrinsic", "phon": "/ɪnˈtrɪnzɪk/", "pos": "adj.", "mean": "固有的；内在的", "ex": "Curiosity is intrinsic to learning.", "ex_zh": "好奇心是学习的内在动力。"},
    {"word": "manipulate", "phon": "/məˈnɪpjuleɪt/", "pos": "v.", "mean": "操纵；处理", "ex": "Do not manipulate the data.", "ex_zh": "不要篡改数据。"},
    {"word": "notwithstanding", "phon": "/ˌnɒtwɪθˈstændɪŋ/", "pos": "prep.", "mean": "尽管；虽然", "ex": "Notwithstanding the risk, they proceeded.", "ex_zh": "尽管有风险，他们仍继续。"},
    {"word": "prevalent", "phon": "/ˈprevələnt/", "pos": "adj.", "mean": "普遍的；流行的", "ex": "This view is prevalent among experts.", "ex_zh": "这种观点在专家中很普遍。"},
    {"word": "readily", "phon": "/ˈredɪli/", "pos": "adv.", "mean": "容易地；乐意地", "ex": "The data is readily available.", "ex_zh": "数据很容易获取。"},
    {"word": "robust", "phon": "/rəʊˈbʌst/", "pos": "adj.", "mean": "强健的；稳健的", "ex": "We need a robust system.", "ex_zh": "我们需要一个稳健的系统。"},
    {"word": "roughly", "phon": "/ˈrʌfli/", "pos": "adv.", "mean": "粗略地；大约", "ex": "The cost is roughly 100 dollars.", "ex_zh": "成本大约是 100 美元。"},
    {"word": "scope", "phon": "/skəʊp/", "pos": "n.", "mean": "范围；余地", "ex": "The scope of the project is clear.", "ex_zh": "项目范围明确。"},
    {"word": "subtle", "phon": "/ˈsʌtl/", "pos": "adj.", "mean": "微妙的；细致的", "ex": "There is a subtle difference.", "ex_zh": "存在一个微妙的差异。"},
    {"word": "thereby", "phon": "/ˈðeəbaɪ/", "pos": "adv.", "mean": "从而；借此", "ex": "He left early, thereby avoiding traffic.", "ex_zh": "他早点离开，从而避开了交通拥堵。"},
    {"word": "uniform", "phon": "/ˈjuːnɪfɔːm/", "pos": "adj.", "mean": "统一的；一致的", "ex": "Apply a uniform standard.", "ex_zh": "采用统一标准。"},
    {"word": "violate", "phon": "/ˈvaɪəleɪt/", "pos": "v.", "mean": "违反；侵犯", "ex": "The act violates the agreement.", "ex_zh": "该行为违反了协议。"},
    {"word": "whereby", "phon": "/weəˈbaɪ/", "pos": "conj.", "mean": "凭此；借以", "ex": "A system whereby users vote.", "ex_zh": "一个用户据此投票的系统。"},
    {"word": "witness", "phon": "/ˈwɪtnəs/", "pos": "v.", "mean": "目击；见证", "ex": "The city witnessed rapid growth.", "ex_zh": "该市见证了快速增长。"},
    {"word": "yield", "phon": "/jiːld/", "pos": "v.", "mean": "产生；屈服", "ex": "The investment yielded high returns.", "ex_zh": "该投资产生了高回报。"},
]
